core/urls.py
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search", SearchView.as_view(), name="search"),
    path("error/", ErrorView.as_view(), name="error"),
    path("about-us/", AboutUsView.as_view(), name="about"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("contact-us/", ContactUsView.as_view(), name="contact"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("refund-policy/", RefundPolicyView.as_view(), name="refund-policy"),
    path("terms-and-conditions/", TermsAndConditionsView.as_view(), name="terms-and-conditions"),
    path("subscribe-newsletter/", SubscribeNewsletterView.as_view(), name="subscribe-newsletter"),
    path("journals", BrowseJournalView.as_view(), name="journals"),
    path("news", NewsListView.as_view(), name="news-list"),
    path("news/<int:pk>/", NewsDetailsView.as_view(), name="news-details"),
    path("announcements", AnnouncementListView.as_view(), name="announcements-list"),
    path("announcements/<int:pk>/", AnnouncementDetailsView.as_view(), name="announcement-details"),
    path("information/<str:url>/", InformationDetailsView.as_view(), name="information-details"),
    path("join/editor/", JoinAsEditorView.as_view(), name="join-as-editor"),
    path("join/reviewer/", JoinAsReviewerView.as_view(), name="join-as-reviewer"),
    path("hard-copy-order/", HardCopyOrderView.as_view(), name="hard-copy-order"),
    
    # Blogs
    path("blogs/", BlogListView.as_view(), name="blog-list"),
    path("blogs/<str:url>/", BlogDetailsView.as_view(), name="blog-details"),

    # Payments
    # path("payments/", PaymentView.as_view(), name="payments"),
    # path("payments/callback/", PaymentCallbackView.as_view(), name="payments-callback"),
    # path("payments/success/", PaymentSuccessView.as_view(), name="payments-success"),
    # path("payments/failed/", PaymentFailedView.as_view(), name="payments-failed"),
    
    # Memberships
    path("membership/apply/", MembershipApplicationView.as_view(), name="membership-apply"),
    path("membership/<str:url>/", MembershipInfoView.as_view(), name="membership-info"),
]

publisher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView


from .sitemap import StaticViewSitemap, ArticleSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "article": ArticleSitemap,
}

urlpatterns = [
    path("sitemap.xml",sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("jet/", include("jet.urls", "jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("", include("core.urls", namespace="core")),
    path("", include("journals.urls", namespace="journals")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/payments.py
import re
import uuid
from django.urls import reverse
from django.db import models
from core.utils import dnb
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.translation import gettext_lazy as _

class Payment(models.Model):
    name = models.CharField(max_length=255, **dnb)
    email = models.CharField(max_length=255, **dnb)
    phone = models.CharField(max_length=31, **dnb)
    country = models.CharField(max_length=31, **dnb)
    amount = models.PositiveBigIntegerField(**dnb)
    currency = models.CharField(max_length=255, **dnb)
    remarks = models.TextField(**dnb)
    rzp_order_id = models.CharField(max_length=255)
    rzp_payment_id = models.CharField(max_length=255)
    rzp_signature = models.CharField(max_length=255)
    payment_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.rzp_order_id}"
    

core/views/blogs.py
from typing import Any
from django.shortcuts import redirect, render
from django.db.models import Q
from django.views.generic import TemplateView, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from core.mixins import PublisherMixin
from core.models import Blog, BlogAuthor


class BlogListView(PublisherMixin, TemplateView):
    template_name = "core/blogs/list.html"

    def get(self, request, *args, **kwargs):
        blogs = Blog.objects.all().order_by("-created_at")
        ctx = {"recent_blogs": blogs[:3], "blogs": blogs.order_by("-views")[3:]}
        return render(request, self.template_name, ctx)


class BlogDetailsView(PublisherMixin, TemplateView):
    template_name = "core/blogs/details.html"

    def get(self, request, *args, **kwargs):
        try:
            blog = Blog.objects.get(url=kwargs.get("url"))
            recommended_blogs = Blog.objects.all().exclude(pk=blog.pk).order_by("-views")[:4]
            ctx = {"blog": blog, "recommended_blogs": recommended_blogs}

            return render(request, self.template_name, ctx)
        except:
            return redirect("core:error")

core/views/core.py
import json
from typing import Any
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.core.serializers import serialize
from django.db.models import Q
from django.views.generic import TemplateView, View, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponse

from core.mixins import PublisherMixin
from core.models import News, Announcement
from core.models.core import Application, Blog, HardCopyOrder, Information, NewsletterSubscription
from journals.models import Journal, Subject, Article
from journals.models.archives import Issue, Volume


class HomeView(PublisherMixin, TemplateView):
    template_name = "core/home.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        journals = Journal.objects.all().order_by("name")
        ctx.update(
            {
                "journals": journals[:6],
                "subjects": Subject.objects.all().order_by("name"),
                "articles": Article.objects.all().order_by("-published")[:7],
                "news": News.objects.all().order_by("-created_on")[:3],
                "blogs": Blog.objects.all().order_by("-created_at")[:4],
                "announcements": Announcement.objects.all().order_by("-created_on")[:3],
            }
        )
        return render(request, self.template_name, ctx)

class ErrorView(PublisherMixin, TemplateView):
    template_name = "core/error.html"

class AboutUsView(PublisherMixin, TemplateView):
    template_name = "core/about.html"

class ContactUsView(PublisherMixin, TemplateView):
    template_name = "core/contact.html"

class PrivacyPolicyView(PublisherMixin, TemplateView):
    template_name = "core/policies/privacy-policy.html"


class RefundPolicyView(PublisherMixin, TemplateView):
    template_name = "core/policies/refund-policy.html"


class TermsAndConditionsView(PublisherMixin, TemplateView):
    template_name = "core/policies/terms-and-conditions.html"


class BrowseJournalView(PublisherMixin, TemplateView):
    template_name = "core/browse-journals.html"

    def get(self, request, *args: Any, **kwargs: Any):
        ctx = self.get_context_data(*args, **kwargs)
        subjects = Subject.objects.all().order_by("name")
        if not request.GET.get("subject"):
            subject_name = "All"
            journals = Journal.objects.all().order_by("name")
        else:
            subject = Subject.objects.get(url=request.GET.get("subject"))
            subject_name = subject.name
            journals = Journal.objects.filter(subject=subject).order_by("name")

        ctx.update(
            {"subjects": subjects, "subject_name": subject_name, "journals": journals}
        )
        return self.render_to_response(ctx)


class NewsListView(PublisherMixin, TemplateView):
    template_name = "core/news/list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        if request.GET.get("query"):
            news_list = News.objects.filter(
                Q(heading__icontains=request.GET.get("query"))
                | Q(content__icontains=request.GET.get("query"))
            )
        else:
            news_list = News.objects.all().order_by("-created_on")

        paginator = Paginator(news_list, self.paginate_by)
        page = request.GET.get("page")

        try:
            news = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            news = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g., 9999), deliver last page.
            news = paginator.page(paginator.num_pages)

        ctx.update(
            {
                "latest_news": News.objects.all().order_by("-created_on")[:3],
                "latest_announcements": Announcement.objects.all().order_by(
                    "-created_on"
                )[:3],
                "news": news,
            }
        )
        return self.render_to_response(ctx)


class NewsDetailsView(PublisherMixin, TemplateView):
    template_name = "core/news/details.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        try:
            news = News.objects.get(pk=kwargs.get("pk"))
        except News.DoesNotExist:
            news = None
        context.update({"news": news})
        return context


class AnnouncementListView(PublisherMixin, TemplateView):
    template_name = "core/announcements/list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        if request.GET.get("query"):
            announcement_list = Announcement.objects.filter(
                Q(heading__icontains=request.GET.get("query"))
                | Q(content__icontains=request.GET.get("query"))
            )
        else:
            announcement_list = Announcement.objects.all().order_by("-created_on")

        paginator = Paginator(announcement_list, self.paginate_by)
        page = request.GET.get("page")

        try:
            announcements = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            announcements = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g., 9999), deliver last page.
            announcements = paginator.page(paginator.num_pages)

        ctx.update(
            {
                "latest_news": News.objects.all().order_by("-created_on")[:3],
                "latest_announcements": Announcement.objects.all().order_by(
                    "-created_on"
                )[:3],
                "announcements": announcements,
            }
        )
        return self.render_to_response(ctx)


class AnnouncementDetailsView(PublisherMixin, TemplateView):
    template_name = "core/announcements/details.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        try:
            announcement = Announcement.objects.get(pk=kwargs.get("pk"))
        except News.DoesNotExist:
            announcement = None
        context.update({"announcement": announcement})
        return context


class InformationDetailsView(PublisherMixin, TemplateView):
    template_name = "core/information/information.html"

    def get(self, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        try:
            informations = Information.objects.all()
            information = informations.get(url=kwargs.get("url"))
        except:
            return redirect("core:error")
        ctx.update({"information": information, "informations": informations})
        return self.render_to_response(ctx)


class SubscribeNewsletterView(PublisherMixin, View):
    def post(self, request, *args, **kwargs):
        referring_url = request.META.get("HTTP_REFERER", None)

        sn = NewsletterSubscription.objects.get_or_create(
            email=request.POST.get("email")
        )

        if referring_url:
            return redirect(referring_url)
        return redirect("core:home")


class SearchView(PublisherMixin, ListView):
    model = Article
    template_name = "core/search.html"
    # context_object_name = "articles"
    # paginate_by = 50

    articleTypes = [
        "All",
        "Research Article",
        "Mini Review Article",
        "Commentary Article",
        "Review Article",
        "Short Communication",
        "Short Commentary Article",
        "Case Report",
        "Case Series",
        "Clinical Images",
        "Editor's pick",
        "Editorial",
        "Elective Report",
        "Letter to the Editor",
        "News Article",
        "News Section",
        "Original Article",
        "Perspective Article",
    ]

    def get_queryset(self):
        article_type = self.request.GET.get("articleType")
        keywords = self.request.GET.get("keywords")
        author = self.request.GET.get("author")
        journal = self.request.GET.get("journal")

        try:
            if article_type and article_type not in self.articleTypes:
                raise Exception("Invalid article type")

            articles = Article.objects.all()
            
            if keywords:
                query = Q()
                if len(keywords.split()) < 3:
                    for word in keywords.split():
                        query |= Q(keywords__icontains=word) | Q(title__icontains=word)
                else:
                    query = Q(title__icontains=keywords) | Q(keywords__icontains=keywords)
                    
                articles = articles.filter(query)

            if author:
                query = Q()
                for word in author.split():
                    query |= Q(authors__first_name=word) | Q(authors__middle_name=word) | Q(authors__last_name=word)
                articles = articles.filter(query)

            if journal and journal != "All":
                journal_obj = Journal.objects.get(name=journal)
                articles = articles.filter(issue__volume__journal=journal_obj)

            if article_type and article_type != "All":
                articles = articles.filter(article_type=article_type)

            return articles

        except Exception as e:
            print(f"Error: {e}")
            return (
                Article.objects.none()
            )
        
    def get_context_data(self, **kwargs):
        # Add variables to the context dictionary
        context = super().get_context_data(**kwargs)
        context["count"] = self.get_queryset().count()
        context["articleType"] = self.request.GET.get("articleType")
        context["keywords"] = self.request.GET.get("keywords")

core/views/membership.py
from typing import Any
from django.shortcuts import redirect, render
from django.db.models import Q
from django.views.generic import TemplateView, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages

from core.mixins import PublisherMixin
from core.models import Membership, Member, MembershipApplication


class MembershipInfoView(PublisherMixin, TemplateView):
    template_name = "core/memberships/membership-info.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        try:
            membership = Membership.objects.get(url=kwargs.get("url"))
            members = Member.objects.filter(membership=membership).order_by("-pk")
            ctx.update({
                "membership": membership,
                "members": members
            })
            return render(request, self.template_name, ctx)
        except:
            return redirect("core:error")


class MembershipApplicationView(PublisherMixin, TemplateView):
    template_name = "core/memberships/application.html"
    
    def post(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        try:
            application = MembershipApplication.objects.create(
                membership_type=request.POST.get("membership_type"),
                name=request.POST.get("name"),
                email=request.POST.get("email"),
                phone=request.POST.get("phone"),
                qualification=request.POST.get("qualification"),
                affiliation=request.POST.get("affiliation"),
                specialization=request.POST.get("specialization"),
                image=request.FILES.get("image")
            )
            application.save()
            messages.success(request, "Application submitted successfully")
        except:
            messages.error(request, "There was an error while processing your application")
        return self.render_to_response(ctx)

templates/core/join-as/editor.html
{% extends "core/base/_base.html" %}

{% block pagetitle %}Join as Editor{% endblock %}

{% block content %}
    <div class="grid grid-cols-1 md:grid-cols-4 gap-5">
        <div class="col-span-1 order-2 md:order-1">
            <div class="bg-white px-5 py-3 flex items-center space-x-2 hover:bg-gray-100 hover:shadow-md cursor-pointer font-bold text-gray-500 hover:text-gray-800" onclick="location.href='{% url "core:join-as-editor" %}'">Join As Editor <i data-feather="arrow-up-right" width="20"></i></div>
            <div class="bg-white px-5 py-3 flex items-center space-x-2 hover:bg-gray-100 hover:shadow-md cursor-pointer font-bold text-gray-500 hover:text-gray-800" onclick="location.href='{% url "core:join-as-reviewer" %}'">Join As Reviewer <i data-feather="arrow-up-right" width="20"></i></div>

            <div class="mt-5 p-5 bg-white">
                <div class="text-gray-600">Benefits</div>
                <ul class="list-inside list-decimal text-sm space-y-2 text-gray-500">
                    <li>An Editor will get prestigious professional recognition and will get certificate and appointment of as Editor which is a professional achievement.</li>
                    <li>An Editor will get 50% waiver for his own manuscripts as main author/corresponding author and will get 25 % waiver in all other publications or as co-author in any our journals.</li>
                    <li>An Editor will get a network of researchers from all over the world.</li>

                </ul>
            </div>

            <div class="mt-5 p-5 bg-white">
                <div class="text-gray-600">Responsibilities</div>
                <ul class="list-inside list-decimal text-sm space-y-2 text-gray-500">
                    <li>An Editor should perform review or cross check the manuscript if assigned by chief editor or publisher.</li>
                    <li>An Editor should assist in decision on acceptance or rejection of manuscript of manuscripts based on reviewer report.</li>
                    <li>An Editor should encourage and promote journals as the best journal to publish in.</li>
                    <li>An Editor need to co-operate, suggest policies, principles and practices which may change from time to time based on expansion plans for the improvement in quality of the journals.</li>
                    <li>An Editor need to assist production team for timely publication of issue.</li>
                </ul>
            </div>
        </div>
        <div class="col-span-1 md:col-span-3 order-1 md:order-2">
            <div class="bg-white p-5">
                <div class="text-gray-400 font-bold">Join as Editor</div>
                
                <div class="my-5">{% include "_messages.html" %}</div>

                <form class="mt-5" method="POST">
                    {% csrf_token %}
                    <div class="max-w-screen-sm">
                        <div class="mb-5">
                            <label for="email" class="block mb-2 text-sm font-medium text-gray-500">Email address</label>
                            <input type="email" id="email" name="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-gray-500 focus:border-gray-500 block w-full p-2" required />
                        </div> 
                        <div class="mb-5">
                            <label for="name" class="block mb-2 text-sm font-medium text-gray-500">Full Name</label>
                            <input type="text" id="name" name="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-gray-500 focus:border-gray-500 block w-full p-2" required />
                        </div>   
                        <div class="mb-5">
                            <label for="phone" class="block mb-2 text-sm font-medium text-gray-500">Contact Number</label>
                            <input type="text" id="phone" name="phone" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-gray-500 focus:border-gray-500 block w-full p-2" required />
                        </div>
                        <div class="mb-5">
                            <label for="spacialization" class="block mb-2 text-sm font-medium text-gray-500">Area of Specialization</label>
                            <input type="text" id="spacialization" name="spacialization" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-gray-500 focus:border-gray-500 block w-full p-2" required />
                        </div>                      
                        <div class="mb-5">
                            <label for="affiliation" class="block mb-2 text-sm font-medium text-gray-500">Complete Affiliation</label>
                            <textarea name="affiliation" id="affiliation" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required></textarea>
                        </div>
                        <div class="mb-5">
                            <label for="publications" class="block mb-2 text-sm font-medium text-gray-500">List of Publications</label>
                            <textarea name="publications" id="publications" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required></textarea>
                        </div>

                        <div class="mb-5">                            
                            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="picture">Upload Profile Picture</label>
                            <input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" id="picture" type="file" name="picture" accept="image/*" required>
                        </div>
                        <div class="mb-5">                            
                            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="resume">Upload Updated Resume</label>
                            <input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" id="resume" type="file" name="resume" accept=".doc, .docx, .pdf" required>
                        </div>
                        
                        <button type="submit" class="text-white bg-primary hover:bg-primaryHover focus:ring-4 focus:outline-none focus:ring-primary font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Apply for Editor</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}