core/urls.py
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search", SearchView.as_view(), name="search"),
    path("error/", ErrorView.as_view(), name="error"),
    path("about-us/", AboutUsView.as_view(), name="about"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("contact-us/", ContactUsView.as_view(), name="contact"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("refund-policy/", RefundPolicyView.as_view(), name="refund-policy"),
    path("terms-and-conditions/", TermsAndConditionsView.as_view(), name="terms-and-conditions"),
    path("subscribe-newsletter/", SubscribeNewsletterView.as_view(), name="subscribe-newsletter"),
    path("journals", BrowseJournalView.as_view(), name="journals"),
    path("news", NewsListView.as_view(), name="news-list"),
    path("news/<int:pk>/", NewsDetailsView.as_view(), name="news-details"),
    path("announcements", AnnouncementListView.as_view(), name="announcements-list"),
    path("announcements/<int:pk>/", AnnouncementDetailsView.as_view(), name="announcement-details"),
    path("information/<str:url>/", InformationDetailsView.as_view(), name="information-details"),
    path("join/editor/", JoinAsEditorView.as_view(), name="join-as-editor"),
    path("join/reviewer/", JoinAsReviewerView.as_view(), name="join-as-reviewer"),
    path("hard-copy-order/", HardCopyOrderView.as_view(), name="hard-copy-order"),
    
    # Blogs
    path("blogs/", BlogListView.as_view(), name="blog-list"),
    path("blogs/<str:url>/", BlogDetailsView.as_view(), name="blog-details"),

    # Payments
    # path("payments/", PaymentView.as_view(), name="payments"),
    # path("payments/callback/", PaymentCallbackView.as_view(), name="payments-callback"),
    # path("payments/success/", PaymentSuccessView.as_view(), name="payments-success"),
    # path("payments/failed/", PaymentFailedView.as_view(), name="payments-failed"),
    
    # Memberships
    path("membership/apply/", MembershipApplicationView.as_view(), name="membership-apply"),
    path("membership/<str:url>/", MembershipInfoView.as_view(), name="membership-info"),
]

journals/urls.py
from django.urls import path
from journals.views import *

app_name = "journals"

urlpatterns = [
    path("download-article/pdf/", ArticleDownloadView.as_view(), name="article-download"),
    path("download-article/xml/<int:article_id>/", ArticleXMLDownloadView.as_view(), name="article-xml-download"),
    path("<str:url>/search", SearchView.as_view(), name="search"),
    path("<str:url>/about/<str:about_type>/", JournalAboutView.as_view(), name="about"),
    path("<str:url>/archives/", JournalArchiveListView.as_view(), name="archives"),
    path("<str:url>/archives/<str:vol>/<str:issue>/", JournalArchiveDetailsView.as_view(), name="archive-details"),
    path("<str:url>/insights", JournalInsightsView.as_view(), name="insights"),
    path("<str:url>/publications", JournalAuthorPublicationsView.as_view(), name="author-publications"),
    path("<str:url>/policy/<str:policy_url>/", JournalPolicyView.as_view(), name="policy"),

    # Special Issue
    path("<str:url>/special-issue/about/", JournalSpecialIssueAbout.as_view(), name="special-issue-about"),
    path("<str:url>/special-issue/propose/", JournalSpecialIssuePropose.as_view(), name="special-issue-propose"),
    path("<str:url>/special-issue/open/", JournalSpecialIssueOpen.as_view(), name="special-issue-open"),
    path("<str:url>/special-issue/published/", JournalSpecialIssuePublished.as_view(), name="special-issue-published"),
    path("<str:url>/special-issue/<str:vol>/<str:issue>/", JournalSpecialIssueDetails.as_view(), name="special-issue-details"),
    path("<str:url>/<str:vol>/<str:issue>/<str:article_url>/", JournalArticleView.as_view(), name="article"),
    path("<str:url>/", JournalDetailView.as_view(), name="home"),

]

publisher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView


from .sitemap import StaticViewSitemap, ArticleSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "article": ArticleSitemap,
}

urlpatterns = [
    path("sitemap.xml",sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("jet/", include("jet.urls", "jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("", include("core.urls", namespace="core")),
    path("", include("journals.urls", namespace="journals")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journals/views/archives.py
import os
import re
import requests
import mimetypes
from django.views import View
from django.conf import settings
from django.views.generic import TemplateView
from django.http import (
    FileResponse,
    HttpResponse,
    HttpResponseNotAllowed,
    StreamingHttpResponse,
)
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404

from journals.models import Volume, Issue, Article, ArticleAuthor
from journals.mixins import JournalMixin


class JournalArchiveListView(JournalMixin, TemplateView):
    template_name = "journals/archives/list.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx.update(
            {
                "volumes": Volume.objects.filter(journal=ctx.get("journal")).order_by(
                    "-year"
                )
            }
        )
        return self.render_to_response(ctx)


class JournalArchiveDetailsView(JournalMixin, TemplateView):
    template_name = "journals/archives/details.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        try:
            issue = Issue.objects.get(id=kwargs.get("issue"))
            ctx.update(
                {
                    "articles": Article.objects.filter(issue=issue).order_by(
                        "-published"
                    ),
                    "volume": issue.volume,
                    "issue": issue,
                }
            )
        except:
            return redirect("error")
        return self.render_to_response(ctx)


class JournalArticleView(JournalMixin, TemplateView):
    template_name = "journals/archives/article.html"

    def split_keywords(self, article: Article):
        if article.keywords:
            split_list = re.split(r"(?<!^);|(?!^),", article.keywords)
            return [word.lstrip().rstrip() for word in split_list if word.strip()]
        else:
            return []

    def get(self, request, *args, **kwargs):
        try:
            ctx = self.get_context_data(**kwargs)
            article = Article.objects.get(url=kwargs.get("article_url"))
            article.views += 1
            article.save()
            journal = article.issue.volume.journal
            ctx["recommended"] = Article.objects.filter(
                issue__volume__journal=journal, keywords__icontains=article.keywords
            ).exclude(id=article.id)[:5]

            if not ctx["recommended"]:
                ctx["recommended"] = (
                    Article.objects.filter(issue__volume__journal=journal)
                    .order_by("views")
                    .exclude(id=article.id)[:4]
                )

            affiliations = {}
            aff_counter = 1
            for author in ArticleAuthor.objects.filter(article=article):
                if author.affiliation not in affiliations:
                    affiliations.update({author.affiliation: aff_counter})
                    aff_counter += 1
            authors = []
            for author in ArticleAuthor.objects.filter(article=article):
                temp = author.__dict__
                temp.update(
                    {
                        "full_name": author.full_name,
                        "author_affiliation_id": (
                            affiliations.get(author.affiliation)
                            if author.affiliation
                            else None
                        ),
                    }
                )
                authors.append(temp)
            ctx.update(
                {
                    "authors": authors,
                    "affiliations": affiliations,
                    "article": article,
                    "keywords": self.split_keywords(article),
                }
            )
        except Exception as e:
            print(e)
            return redirect("core:error")
        return self.render_to_response(ctx)


class ArticleXMLDownloadView(View):
    def get(self, request, *args, **kwargs):
        try:
            article = Article.objects.get(id=kwargs.get("article_id"))
            article.downloads += 1
            article.save()

            file_url = article.xml.url

            response = requests.get(file_url, stream=True)
            response.raise_for_status()  # Ensure the request was successful

            filename = os.path.basename(file_url)
            mime_type, _ = mimetypes.guess_type(filename)

            streaming_response = StreamingHttpResponse(
                response.iter_content(chunk_size=8192),
                content_type=mime_type or "application/pdf",
            )
            streaming_response["Content-Disposition"] = (
                f'attachment; filename="{filename}"'
            )
            return streaming_response
        except:
            return redirect("error")


class ArticleDownloadView(View):

    def post(self, request, *args, **kwargs):
        article = Article.objects.get(id=int(request.POST.get("article_id")))
        article.downloads += 1
        article.save()

        self.send_subscriber(request.POST.get("email"))

        try:
            file_url = article.pdf.url

            response = requests.get(file_url, stream=True)
            response.raise_for_status()  # Ensure the request was successful

            filename = os.path.basename(file_url)
            mime_type, _ = mimetypes.guess_type(filename)

            streaming_response = StreamingHttpResponse(
                response.iter_content(chunk_size=8192),
                content_type=mime_type or "application/pdf",
            )
            streaming_response["Content-Disposition"] = (
                f'attachment; filename="{filename}"'
            )
            return streaming_response
        except:
            return redirect(
                reverse(
                    "journals:article",
                    kwargs={
                        "url": article.issue.volume.journal.url,
                        "vol": article.issue.volume.pk,
                        "issue": article.issue.pk,
                        "article_url": article.url,
                    },
                )
            )

    def send_subscriber(self, email):
        IARCON_API_BASE = os.getenv("IARCON_API_BASE")
        url = f"{IARCON_API_BASE}/webapp/subscriber"
        data = {"email": email, "from": "iarconsortium.org"}
        AUTH_TOKEN = os.getenv("IARCON_TOKEN")
        headers = {"Authorization": AUTH_TOKEN, "Content-Type": "application/json"}
        requests.post(url, json=data, headers=headers)
        
    def get(self, request, *args, **kwargs):
        return HttpResponseNotAllowed(["POST"])

journals/views/journal.py
from django.views.generic import TemplateView
from itertools import chain
from django.db.models import Q, Func, Value, CharField, functions
from django.shortcuts import redirect

from core.mixins import PublisherMixin
from journals.models import (
    Indexing,
    EditorialBoard,
    Article,
    JournalNews,
    JournalAnnouncement,
)
from journals.mixins import JournalMixin


class JournalDetailView(JournalMixin, TemplateView):
    template_name = "journals/home.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        articles = Article.objects.filter(issue__volume__journal=ctx.get("journal"))
        ctx.update(
            {
                "editor": EditorialBoard.objects.filter(
                    journal=ctx.get("journal"), editor_type="editor_in_chief"
                ).first(),
                "latest_published": articles.order_by("-published")[:8],
                "most_downloaded": articles.order_by("-downloads")[:8],
                "most_popular": articles.order_by("-views")[:8],
                "news": JournalNews.objects.filter(journal=ctx.get("journal")).order_by(
                    "-created_on"
                )[:2],
                "announcements": JournalAnnouncement.objects.filter(
                    journal=ctx.get("journal")
                ).order_by("-created_on")[:2],
                "indexings": Indexing.objects.filter(
                    journal=ctx.get("journal"), show_in_home=True
                ).order_by("name"),
                "editor_in_chiefs": EditorialBoard.objects.filter(
                    journal=ctx.get("journal"), editor_type="editor_in_chief"
                ),
            }
        )
        return self.render_to_response(ctx)


class JournalInsightsView(JournalMixin, TemplateView):
    template_name = "journals/insights.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        print(ctx)
        indexings = Indexing.objects.filter(journal=ctx.get("journal")).order_by("name")
        ctx.update({"indexings": indexings})
        return self.render_to_response(ctx)


class JournalAboutView(JournalMixin, TemplateView):
    template_name = "journals/about/about.html"
    about_type_map = {
        "aim-and-scope": "Aim & Scope",
        "editorial-board": "Editorial Board",
        "news": "News",
        "announcements": "Announcements",
    }

    def get(self, request, *args, **kwargs):
        about_type = kwargs.get("about_type")
        if about_type not in self.about_type_map.keys():
            return redirect("core:error")
        ctx = self.get_context_data(**kwargs)
        ctx.update(
            {
                "about_type": about_type,
                "about_type_label": self.about_type_map[about_type],
            }
        )

        if about_type == "editorial-board":
            editorial_board = EditorialBoard.objects.filter(journal=ctx.get("journal"))
            ctx.update(
                {
                    "editor_in_chief": editorial_board.filter(
                        editor_type="editor_in_chief"
                    ),
                    "associate_editor": editorial_board.filter(
                        editor_type="associate_editor"
                    ),
                    "editorial_board_member": editorial_board.filter(
                        editor_type="editorial_board_member"
                    ),
                    "advisory_board_member": editorial_board.filter(
                        editor_type="advisory_board_member"
                    ),
                    "managing_editor": editorial_board.filter(
                        editor_type="managing_editor"
                    ),
                    "reviewers": editorial_board.filter(
                        editor_type="reviewer"
                    ),
                }
            )
        elif about_type == "news":
            ctx.update({"news": None})
        elif about_type == "announcements":
            ctx.update({"announcements": None})
        return self.render_to_response(ctx)


class SearchView(JournalMixin, TemplateView):
    template_name = "journals/search/results.html"

    def get(self, request, *args, **kwargs):
        if not request.GET.get("q"):
            return redirect("core:error")
        # try:
        results = None
        ctx = self.get_context_data(**kwargs)
        query = request.GET.get("q")
        all_articles = Article.objects.filter(
            issue__volume__journal=ctx["journal"]
        ).filter(
            Q(title__icontains=query)
            | Q(abstract__icontains=query)
            | Q(keywords__icontains=query)
        )
        author_articles = Article.objects.filter(authors__first_name__icontains=query)
        count = all_articles.count() + author_articles.count()
        articles = list(chain(all_articles, author_articles))
        ctx.update({"query": query, "articles": articles, "count": count})
        return self.render_to_response(ctx)
        # except:
        #     return redirect("core:error")

templates/journals/archives/details.html
{% extends "journals/base/_base.html" %}

{% block pagetitle %}Archives{% endblock %}

{% block content %}
<div class="container py-10 min-h-screen">
    <div class="mt-5 grid grid-cols-1 md:grid-cols-4 gap-5 md:gap-10">
        <div class="col-span-1">
            <div class="text-xl lg:text-4xl">{{ volume.name }} {{ issue.name }}</div>
            <div class="">{{ issue.month }} {{ volume.year }}</div>
            <div class="">
                {% include "journals/blocks/ad-space-2.html" %}
              </div>
        </div>
        <div class="col-span-1 md:col-span-3">
            {% if articles %}
            {% for article in articles %}
                {% include "journals/blocks/article-list.html" %}
            {% endfor %}
            {% else %}
            <div class="">No Articles</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/journals/archives/list.html
{% extends "journals/base/_base.html" %}

{% block pagetitle %}Archives{% endblock %}

{% block content %}
<div class="container py-10 min-h-screen">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-5 md:gap-10">
        <div class="col-span-1">
          <div class="lg:sticky lg:top-48">
            <div class="text-xl lg:text-4xl">All Volumes &amp; Issues</div>
            <div class="flex items-center text-primary underline-offset-4 hover:underline cursor-pointer" onclick="location.href='{% url "journals:special-issue-about" url=journal.url %}'">
                View Special Issues
                <i data-feather="arrow-up-right" class="w-4"></i>
            </div>
            <div class="">
              {% include "journals/blocks/ad-space-2.html" %}
            </div>
          </div>

        </div>
        <div class="col-span-1 md:col-span-3">
            <div id="accordion-flush" data-accordion="collapse" data-active-classes="bg-white dark:bg-gray-900 text-gray-900 dark:text-white" data-inactive-classes="text-gray-500 dark:text-gray-400">
                {% comment %} <h2 id="accordion-flush-heading-1">
                    <button type="button" class="flex items-center justify-between w-full py-5 font-medium text-left text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400" data-accordion-target="#accordion-flush-body-1" aria-expanded="true" aria-controls="accordion-flush-body-1">
                    <span>What is Flowbite?</span>
                    <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
                    </svg>
                    </button>
                </h2>
                <div id="accordion-flush-body-1" class="hidden" aria-labelledby="accordion-flush-heading-1">
                    <div class="py-5 border-b border-gray-200 dark:border-gray-700">
                    <p class="mb-2 text-gray-500 dark:text-gray-400">Flowbite is an open-source library of interactive components built on top of Tailwind CSS including buttons, dropdowns, modals, navbars, and more.</p>
                    <p class="text-gray-500 dark:text-gray-400">Check out this guide to learn how to <a href="/docs/getting-started/introduction/" class="text-blue-600 dark:text-blue-500 hover:underline">get started</a> and start developing websites even faster with components on top of Tailwind CSS.</p>
                    </div>
                </div> {% endcomment %}

                {% for v in volumes %}
              <h2 id="accordion-collapse-heading-{{v.id}}">
                <button type="button" class="flex items-center justify-between w-full px-5 py-3 font-medium text-left border-b text-gray-700 hover:bg-gray-200" data-accordion-target="#accordion-collapse-body-{{v.id}}" aria-expanded="false" aria-controls="accordion-collapse-body-{{v.id}}">
                  <span class="font-medium">{{ v.name }} ({{ v.year }})</span>
                  <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
                  </svg>
                </button>
              </h2>
              <div id="accordion-collapse-body-{{v.id}}" class="hidden" aria-labelledby="accordion-collapse-heading-{{v.id}}">
                <div class="py-3">
                  {% for issue in v.issues.all|dictsortreversed:"id" %}
                    {% if not issue.is_special_issue %}
                      {% if issue.download_pdf %}
                        <a class="flex mt-2 cursor-pointer" href="{{ issue.download_pdf.url }}" download>{{ issue.name }} <i data-feather="download" class="ml-2 w-4 text-red-500"></i></a>
                      {% else %}
                        <div class="mt-2 px-5 cursor-pointer underline-offset-4 hover:underline hover:text-primary" onclick="location.href='{% url "journals:archive-details" url=journal.url vol=v.id issue=issue.id %}'">{{ issue.name }}</div>
                      {% endif %}
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
              {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}