core/urls.py
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search", SearchView.as_view(), name="search"),
    path("error/", ErrorView.as_view(), name="error"),
    path("about-us/", AboutUsView.as_view(), name="about"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("contact-us/", ContactUsView.as_view(), name="contact"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("refund-policy/", RefundPolicyView.as_view(), name="refund-policy"),
    path("terms-and-conditions/", TermsAndConditionsView.as_view(), name="terms-and-conditions"),
    path("subscribe-newsletter/", SubscribeNewsletterView.as_view(), name="subscribe-newsletter"),
    path("journals", BrowseJournalView.as_view(), name="journals"),
    path("news", NewsListView.as_view(), name="news-list"),
    path("news/<int:pk>/", NewsDetailsView.as_view(), name="news-details"),
    path("announcements", AnnouncementListView.as_view(), name="announcements-list"),
    path("announcements/<int:pk>/", AnnouncementDetailsView.as_view(), name="announcement-details"),
    path("information/<str:url>/", InformationDetailsView.as_view(), name="information-details"),
    path("join/editor/", JoinAsEditorView.as_view(), name="join-as-editor"),
    path("join/reviewer/", JoinAsReviewerView.as_view(), name="join-as-reviewer"),
    path("hard-copy-order/", HardCopyOrderView.as_view(), name="hard-copy-order"),
    
    # Blogs
    path("blogs/", BlogListView.as_view(), name="blog-list"),
    path("blogs/<str:url>/", BlogDetailsView.as_view(), name="blog-details"),

    # Payments
    # path("payments/", PaymentView.as_view(), name="payments"),
    # path("payments/callback/", PaymentCallbackView.as_view(), name="payments-callback"),
    # path("payments/success/", PaymentSuccessView.as_view(), name="payments-success"),
    # path("payments/failed/", PaymentFailedView.as_view(), name="payments-failed"),
    
    # Memberships
    path("membership/apply/", MembershipApplicationView.as_view(), name="membership-apply"),
    path("membership/<str:url>/", MembershipInfoView.as_view(), name="membership-info"),
]

publisher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView


from .sitemap import StaticViewSitemap, ArticleSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "article": ArticleSitemap,
}

urlpatterns = [
    path("sitemap.xml",sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("jet/", include("jet.urls", "jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("", include("core.urls", namespace="core")),
    path("", include("journals.urls", namespace="journals")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/payments.py
import re
import uuid
from django.urls import reverse
from django.db import models
from core.utils import dnb
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.translation import gettext_lazy as _

class Payment(models.Model):
    name = models.CharField(max_length=255, **dnb)
    email = models.CharField(max_length=255, **dnb)
    phone = models.CharField(max_length=31, **dnb)
    country = models.CharField(max_length=31, **dnb)
    amount = models.PositiveBigIntegerField(**dnb)
    currency = models.CharField(max_length=255, **dnb)
    remarks = models.TextField(**dnb)
    rzp_order_id = models.CharField(max_length=255)
    rzp_payment_id = models.CharField(max_length=255)
    rzp_signature = models.CharField(max_length=255)
    payment_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.rzp_order_id}"
    

core/views/blogs.py
from typing import Any
from django.shortcuts import redirect, render
from django.db.models import Q
from django.views.generic import TemplateView, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from core.mixins import PublisherMixin
from core.models import Blog, BlogAuthor


class BlogListView(PublisherMixin, TemplateView):
    template_name = "core/blogs/list.html"

    def get(self, request, *args, **kwargs):
        blogs = Blog.objects.all().order_by("-created_at")
        ctx = {"recent_blogs": blogs[:3], "blogs": blogs.order_by("-views")[3:]}
        return render(request, self.template_name, ctx)


class BlogDetailsView(PublisherMixin, TemplateView):
    template_name = "core/blogs/details.html"

    def get(self, request, *args, **kwargs):
        try:
            blog = Blog.objects.get(url=kwargs.get("url"))
            recommended_blogs = Blog.objects.all().exclude(pk=blog.pk).order_by("-views")[:4]
            ctx = {"blog": blog, "recommended_blogs": recommended_blogs}

            return render(request, self.template_name, ctx)
        except:
            return redirect("core:error")

core/views/core.py
import json
from typing import Any
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.core.serializers import serialize
from django.db.models import Q
from django.views.generic import TemplateView, View, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponse

from core.mixins import PublisherMixin
from core.models import News, Announcement
from core.models.core import Application, Blog, HardCopyOrder, Information, NewsletterSubscription
from journals.models import Journal, Subject, Article
from journals.models.archives import Issue, Volume


class HomeView(PublisherMixin, TemplateView):
    template_name = "core/home.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        journals = Journal.objects.all().order_by("name")
        ctx.update(
            {
                "journals": journals[:6],
                "subjects": Subject.objects.all().order_by("name"),
                "articles": Article.objects.all().order_by("-published")[:7],
                "news": News.objects.all().order_by("-created_on")[:3],
                "blogs": Blog.objects.all().order_by("-created_at")[:4],
                "announcements": Announcement.objects.all().order_by("-created_on")[:3],
            }
        )
        return render(request, self.template_name, ctx)

class ErrorView(PublisherMixin, TemplateView):
    template_name = "core/error.html"

class AboutUsView(PublisherMixin, TemplateView):
    template_name = "core/about.html"

class ContactUsView(PublisherMixin, TemplateView):
    template_name = "core/contact.html"

class PrivacyPolicyView(PublisherMixin, TemplateView):
    template_name = "core/policies/privacy-policy.html"


class RefundPolicyView(PublisherMixin, TemplateView):
    template_name = "core/policies/refund-policy.html"


class TermsAndConditionsView(PublisherMixin, TemplateView):
    template_name = "core/policies/terms-and-conditions.html"


class BrowseJournalView(PublisherMixin, TemplateView):
    template_name = "core/browse-journals.html"

    def get(self, request, *args: Any, **kwargs: Any):
        ctx = self.get_context_data(*args, **kwargs)
        subjects = Subject.objects.all().order_by("name")
        if not request.GET.get("subject"):
            subject_name = "All"
            journals = Journal.objects.all().order_by("name")
        else:
            subject = Subject.objects.get(url=request.GET.get("subject"))
            subject_name = subject.name
            journals = Journal.objects.filter(subject=subject).order_by("name")

        ctx.update(
            {"subjects": subjects, "subject_name": subject_name, "journals": journals}
        )
        return self.render_to_response(ctx)


class NewsListView(PublisherMixin, TemplateView):
    template_name = "core/news/list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        if request.GET.get("query"):
            news_list = News.objects.filter(
                Q(heading__icontains=request.GET.get("query"))
                | Q(content__icontains=request.GET.get("query"))
            )
        else:
            news_list = News.objects.all().order_by("-created_on")

        paginator = Paginator(news_list, self.paginate_by)
        page = request.GET.get("page")

        try:
            news = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            news = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g., 9999), deliver last page.
            news = paginator.page(paginator.num_pages)

        ctx.update(
            {
                "latest_news": News.objects.all().order_by("-created_on")[:3],
                "latest_announcements": Announcement.objects.all().order_by(
                    "-created_on"
                )[:3],
                "news": news,
            }
        )
        return self.render_to_response(ctx)


class NewsDetailsView(PublisherMixin, TemplateView):
    template_name = "core/news/details.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        try:
            news = News.objects.get(pk=kwargs.get("pk"))
        except News.DoesNotExist:
            news = None
        context.update({"news": news})
        return context


class AnnouncementListView(PublisherMixin, TemplateView):
    template_name = "core/announcements/list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        if request.GET.get("query"):
            announcement_list = Announcement.objects.filter(
                Q(heading__icontains=request.GET.get("query"))
                | Q(content__icontains=request.GET.get("query"))
            )
        else:
            announcement_list = Announcement.objects.all().order_by("-created_on")

        paginator = Paginator(announcement_list, self.paginate_by)
        page = request.GET.get("page")

        try:
            announcements = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            announcements = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g., 9999), deliver last page.
            announcements = paginator.page(paginator.num_pages)

        ctx.update(
            {
                "latest_news": News.objects.all().order_by("-created_on")[:3],
                "latest_announcements": Announcement.objects.all().order_by(
                    "-created_on"
                )[:3],
                "announcements": announcements,
            }
        )
        return self.render_to_response(ctx)


class AnnouncementDetailsView(PublisherMixin, TemplateView):
    template_name = "core/announcements/details.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        try:
            announcement = Announcement.objects.get(pk=kwargs.get("pk"))
        except News.DoesNotExist:
            announcement = None
        context.update({"announcement": announcement})
        return context


class InformationDetailsView(PublisherMixin, TemplateView):
    template_name = "core/information/information.html"

    def get(self, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        try:
            informations = Information.objects.all()
            information = informations.get(url=kwargs.get("url"))
        except:
            return redirect("core:error")
        ctx.update({"information": information, "informations": informations})
        return self.render_to_response(ctx)


class SubscribeNewsletterView(PublisherMixin, View):
    def post(self, request, *args, **kwargs):
        referring_url = request.META.get("HTTP_REFERER", None)

        sn = NewsletterSubscription.objects.get_or_create(
            email=request.POST.get("email")
        )

        if referring_url:
            return redirect(referring_url)
        return redirect("core:home")


class SearchView(PublisherMixin, ListView):
    model = Article
    template_name = "core/search.html"
    # context_object_name = "articles"
    # paginate_by = 50

    articleTypes = [
        "All",
        "Research Article",
        "Mini Review Article",
        "Commentary Article",
        "Review Article",
        "Short Communication",
        "Short Commentary Article",
        "Case Report",
        "Case Series",
        "Clinical Images",
        "Editor's pick",
        "Editorial",
        "Elective Report",
        "Letter to the Editor",
        "News Article",
        "News Section",
        "Original Article",
        "Perspective Article",
    ]

    def get_queryset(self):
        article_type = self.request.GET.get("articleType")
        keywords = self.request.GET.get("keywords")
        author = self.request.GET.get("author")
        journal = self.request.GET.get("journal")

        try:
            if article_type and article_type not in self.articleTypes:
                raise Exception("Invalid article type")

            articles = Article.objects.all()
            
            if keywords:
                query = Q()
                if len(keywords.split()) < 3:
                    for word in keywords.split():
                        query |= Q(keywords__icontains=word) | Q(title__icontains=word)
                else:
                    query = Q(title__icontains=keywords) | Q(keywords__icontains=keywords)
                    
                articles = articles.filter(query)

            if author:
                query = Q()
                for word in author.split():
                    query |= Q(authors__first_name=word) | Q(authors__middle_name=word) | Q(authors__last_name=word)
                articles = articles.filter(query)

            if journal and journal != "All":
                journal_obj = Journal.objects.get(name=journal)
                articles = articles.filter(issue__volume__journal=journal_obj)

            if article_type and article_type != "All":
                articles = articles.filter(article_type=article_type)

            return articles

        except Exception as e:
            print(f"Error: {e}")
            return (
                Article.objects.none()
            )
        
    def get_context_data(self, **kwargs):
        # Add variables to the context dictionary
        context = super().get_context_data(**kwargs)
        context["count"] = self.get_queryset().count()
        context["articleType"] = self.request.GET.get("articleType")
        context["keywords"] = self.request.GET.get("keywords")

core/views/membership.py
from typing import Any
from django.shortcuts import redirect, render
from django.db.models import Q
from django.views.generic import TemplateView, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages

from core.mixins import PublisherMixin
from core.models import Membership, Member, MembershipApplication


class MembershipInfoView(PublisherMixin, TemplateView):
    template_name = "core/memberships/membership-info.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        try:
            membership = Membership.objects.get(url=kwargs.get("url"))
            members = Member.objects.filter(membership=membership).order_by("-pk")
            ctx.update({
                "membership": membership,
                "members": members
            })
            return render(request, self.template_name, ctx)
        except:
            return redirect("core:error")


class MembershipApplicationView(PublisherMixin, TemplateView):
    template_name = "core/memberships/application.html"
    
    def post(self, request, *args, **kwargs):
        ctx = self.get_context_data(*args, **kwargs)
        try:
            application = MembershipApplication.objects.create(
                membership_type=request.POST.get("membership_type"),
                name=request.POST.get("name"),
                email=request.POST.get("email"),
                phone=request.POST.get("phone"),
                qualification=request.POST.get("qualification"),
                affiliation=request.POST.get("affiliation"),
                specialization=request.POST.get("specialization"),
                image=request.FILES.get("image")
            )
            application.save()
            messages.success(request, "Application submitted successfully")
        except:
            messages.error(request, "There was an error while processing your application")
        return self.render_to_response(ctx)

templates/core/about.html
{% extends "core/base/_base.html" %}
{% load solo_tags %}

{% block pagetitle %}About Us{% endblock %}

{% block content %}
    <div class="grid grid-cols-1 md:grid-cols-4 gap-5">
        <div class="col-span-1 order-2 md:order-1 text-sm">
            <div class="w-full px-5 py-2 hover:text-gray-600 hover:underline cursor-pointer" onclick="location.href='{% url "core:about" %}'">About Us</div>
            <div class="w-full px-5 py-2 hover:text-gray-600 hover:underline cursor-pointer" onclick="location.href='{% url "core:contact" %}'">Contact Us</div>
        </div>
        <div class="col-span-1 md:col-span-3 order-1 md:order-2 pb-20">
            <div class="text-xl">About Us</div>
            <div class="mt-10">
                {% get_solo 'core.SiteConfiguration' as site_config %}
                {{ site_config.about|safe }}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/browse-journals.html
{% extends 'core/base/_base.html' %}
{% load static %}
{% load solo_tags %}

{% block pagetitle %}Browse Journals{% endblock %}


{% block content %}
<div class="grid grid-cols-1 lg:grid-cols-4 gap-5">
    <div class="col-span-1 bg-white p-5">
        <div class="hover:underline cursor-pointer hover:text-primary text-cyan-700" onclick="location.href='{% url "core:journals" %}'">View All Journals</div>

        {% if subjects %}
        <div class="mt-5 pt-5 border-t font-bold text-gray-400">Subjects</div>

        <div class="mt-3 flex justify-start items-start flex-col mb-5">
            {% for s in subjects %}
                <div class="hover:underline cursor-pointer hover:text-primary p-3 border-b w-full" onclick="location.href='{% url "core:journals" %}?subject={{s.url}}'">{{ s.name }}</div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

    <div class="col-span-1 lg:col-span-3">
        <div class="bg-white p-5">
            {% get_solo 'core.SiteConfiguration' as site_config %}
            <div class="text-xl">All Journals</div>

            <div class="mt-5">{{ subject_name }} Journals</div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
            {% for journal in journals %}
            <div class="col-span-1">
                {% include "core/blocks/journal-box.html" %}
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/core/contact.html
{% extends "core/base/_base.html" %}
{% load solo_tags %}

{% block pagetitle %}Contactt Us{% endblock %}

{% block content %}
    <div class="grid grid-cols-1 md:grid-cols-4 gap-5">
        <div class="col-span-1 order-2 md:order-1 text-sm">
            <div class="w-full px-5 py-2 hover:text-gray-600 hover:underline cursor-pointer" onclick="location.href='{% url "core:about" %}'">About Us</div>
            <div class="w-full px-5 py-2 hover:text-gray-600 hover:underline cursor-pointer" onclick="location.href='{% url "core:contact" %}'">Contact Us</div>
        </div>
        <div class="col-span-1 md:col-span-3 order-1 md:order-2">
            <div class="text-xl">Contact Us</div>
            {% get_solo 'core.SiteConfiguration' as site_config %}
            <div class="mt-20">
                {{ site_config.contact_us|safe }}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/error.html
{% extends 'core/base/_base.html' %}
{% load static %}

{% block pagetitle %}Error{% endblock %}


{% block content %}
<div class="p-10 bg-[#FFCAEC] flex flex-col md:flex-row justify-center items-center w-full">
    <img src="{% static "images/error.svg" %}" class="md:w-1/3 rounded-md"/>
    <div class="">
        <div class="text-3xl md:text-5xl font-bold">Something went wrong!</div>
        <div class="">Our ninjas are already on it.</div>
    </div>
</div>
{% endblock %}

templates/core/home.html
{% extends 'core/base/_base.html' %}
{% load static %}
{% load solo_tags %}

{% block pagetitle %}Home{% endblock %}

{% block content %}
<div class="grid grid-cols-1 lg:grid-cols-4 gap-5">
    <div class="col-span-1 bg-white p-5">
        
        {% if subjects %}
        <span class="text-xl">Browse Subjects</span>

        <div class="mt-3 flex justify-start items-start flex-col mb-5">
            {% for s in subjects %}
                <div class="flex items-center hover:underline cursor-pointer text-gray-6        00 hover:text-primary py-2 border-b w-full" onclick="location.href='{% url "core:journals" %}?subject={{s.url}}'">{{ s.name }} <i data-feather="arrow-up-right" width="16"></i></div>
            {% endfor %}
        </div>
        {% endif %}

        {% if journals %}
        <span class="mt-10 text-xl">Recommended Journals</span>

        <div class="pl-3">
            {% for j in journals %}
                <div class="grid grid-cols-6 mt-3 gap-3 group">
                    <div class="col-span-2">
                        <img src="{{ j.thumbnail.url }}" />
                    </div>
                    <div class="col-span-4 text-sm group-hover:underline group-hover:text-primary cursor-pointer" onclick="location.href='{% url "journals:home" url=j.url %}'">
                        {{ j.name }}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- AD SPACE 2-->
        {% include "core/blocks/ad-space-2.html" %}
        
    </div>
    <div class="col-span-1 lg:col-span-2 space-y-5">
        {% get_solo 'core.SiteConfiguration' as site_config %}
        <div class="bg-white p-5">
            <div class="text-xl">About <span class="font-medium">{{ site_config.site_name }}</span></div>
            <div class="mt-5">{{ site_config.about|safe|truncatewords_html:50 }}</div>
            <div class="text-sm cursor-pointer text-primary hover:underline hover:text-secondary" onclick="location.href='{% url "core:about" %}'">Read more</div>
        </div>

        <!-- AD SPACE 1-->
        {% include "core/blocks/ad-space-1.html" %}
        


        <div class="bg-white p-5 mt-5">
            <div class="mb-5 font-medium text-xl">Recent Articles</div>
            {% if articles %}
            {% for article in articles %}
                {% include "core/blocks/article-list.html" %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="col-span-1 space-y-5">
        {% if announcements %}
        <div class="p-5 bg-white">
            <div class="flex items-center w-full">
                <div class="font-medium flex-grow">Announcements</div>
                <div class="text-gray-500 text-sm cursor-pointer hover:underline" onclick="location.href='{% url "core:announcements-list" %}'">Read All ></div>
            </div>
            {% for a in announcements %}
            <div class="mt-3 flex flex-col justify-start">
                <div class="text-sm">{{ a.created_on|date:"d M, Y"}}</div>
                <div class="font-medium text-sm cursor-pointer text-primary hover:text-primary hover:underline"  onclick="location.href='{% url "core:announcement-details" pk=a.pk %}'">{{ a.heading }}</div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if news %}
        <div class="p-5 bg-white">
            <div class="flex items-center w-full">
                <div class="font-medium flex-grow">News</div>
                <div class="text-gray-500 text-sm cursor-pointer hover:underline" onclick="location.href='{% url "core:news-list" %}'">Read All ></div>
            </div>
            {% for n in news %}
            <div class="mt-3 flex flex-col justify-start">
                <div class="text-sm">{{ n.created_on|date:"d M, Y"}}</div>
                <div class="font-medium text-sm cursor-pointer text-primary hover:text-primary hover:underline" onclick="location.href='{% url "core:news-details" pk=n.pk %}'">{{ n.heading }}</div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="p-5 bg-white">
            <div class="font-medium">Special Issues</div>
        </div>

        <!-- AD SPACE 2-->
        {% include "core/blocks/ad-space-3.html" %}
        
    </div>
</div>

{% if blogs %}
<div class="mt-5 bg-white p-5">
    <div class="flex items-center w-full">
        <div class="font-medium flex-grow text-xl">Read Our Blogs</div>
        <div class="text-gray-500 text-sm cursor-pointer hover:underline" onclick="location.href='{% url "core:blog-list" %}'">Read All ></div>
    </div>
    <div class="mt-5 grid grid-cols-1 md:grid-cols-4 gap-5">
        <div class="col-span-1 md:col-span-2">
            {% if blogs.0 %}
            <div class="border hover:shadow-xl rounded-sm cursor-pointer transition-all duration-300" onclick="location.href='{% url "core:blog-details" url=blogs.0.url %}'">
                <img src="{{ blogs.0.featured_image.url }}" class="w-full" />
                <div class="p-5">
                    <div class="mt-2 text-sm text-gray-500 flex justify-start items-center space-x-2">
                        {% for a in blogs.0.blog_authors.all %}
                            <div class="">{{a.first_name}} {{ a.last_name}}</div>
                        {% endfor %}
                        <div class="">•</div>
                        <div class="">{{ blogs.0.created_at|date:"d M, Y"}}</div>
                    </div>
                    <div class="font-medium text-3xl">{{ blogs.0.heading }}</div>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-span-1 md:col-span-2">
            {% if blogs.1 %}
            <div class="border hover:shadow-xl rounded-sm cursor-pointer transition-all duration-300" onclick="location.href='{% url "core:blog-details" url=blogs.1.url %}'">
                <div class="grid grid-cols-1 md:grid-cols-5 gap-3">
                    <div class="col-span-1 md:col-span-2">
                        <img src="{{ blogs.1.featured_image.url }}" class="w-full" />
                    </div>
                    <div class="col-span-1 md:col-span-3 p-3">
                        <div class="text-sm text-gray-500 flex justify-start items-center space-x-2">
                            {% for a in blogs.1.blog_authors.all %}
                                <div class="">{{a.first_name}} {{ a.last_name}}</div>
                            {% endfor %}
                            <div class="">•</div>
                            <div class="">{{ blogs.1.created_at|date:"d M, Y"}}</div>
                        </div>
                        <div class="font-medium text-xl">{{ blogs.1.heading }}</div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if blogs.2 %}
            <div class="mt-5 border hover:shadow-xl rounded-sm cursor-pointer transition-all duration-300" onclick="location.href='{% url "core:blog-details" url=blogs.2.url %}'">
                <div class="grid grid-cols-1 md:grid-cols-5 gap-3">
                    <div class="col-span-1 md:col-span-2">
                        <img src="{{ blogs.2.featured_image.url }}" class="w-full" />
                    </div>
                    <div class="col-span-1 md:col-span-3 p-3">
                        <div class="text-sm text-gray-500 flex justify-start items-center space-x-2">
                            {% for a in blogs.2.blog_authors.all %}
                                <div class="">{{a.first_name}} {{ a.last_name}}</div>
                            {% endfor %}
                            <div class="">•</div>
                            <div class="">{{ blogs.2.created_at|date:"d M, Y"}}</div>
                        </div>
                        <div class="mt-1 font-medium text-xl">{{ blogs.2.heading }}</div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if blogs.3 %}
            <div class="mt-5 border hover:shadow-xl rounded-sm cursor-pointer transition-all duration-300" onclick="location.href='{% url "core:blog-details" url=blogs.3.url %}'">
                <div class="grid grid-cols-1 md:grid-cols-5 gap-3">
                    <div class="col-span-1 md:col-span-2">
                        <img src="{{ blogs.3.featured_image.url }}" class="w-full" />
                    </div>
                    <div class="col-span-1 md:col-span-3 p-3">
                        <div class="text-sm text-gray-500 flex justify-start items-center space-x-2">
                            {% for a in blogs.3.blog_authors.all %}
                                <div class="">{{a.first_name}} {{ a.last_name}}</div>
                            {% endfor %}
                            <div class="">•</div>
                            <div class="">{{ blogs.3.created_at|date:"d M, Y"}}</div>
                        </div>
                        <div class="mt-1 font-medium text-xl">{{ blogs.3.heading }}</div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if blogs.4 %}
            <div class="mt-3 border hover:shadow-xl rounded-sm cursor-pointer transition-all duration-300" onclick="location.href='{% url "core:blog-details" url=blogs.4.url %}'">
                <div class="grid grid-cols-1 md:grid-cols-5 gap-3">
                    <div class="col-span-1 md:col-span-2">
                        <img src="{{ blogs.4.featured_image.url }}" class="w-full" />
                    </div>
                    <div class="col-span-1 md:col-span-3 p-3">
                        <div class="text-sm text-gray-500 flex justify-start items-center space-x-2">
                            {% for a in blogs.4.blog_authors.all %}
                                <div class="">{{a.first_name}} {{ a.last_name}}</div>
                            {% endfor %}
                            <div class="">•</div>
                            <div class="">{{ blogs.4.created_at|date:"d M, Y"}}</div>
                        </div>
                        <div class="mt-1 font-medium text-xl">{{ blogs.4.heading }}</div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endif %}


{% endblock %}