core/urls.py
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("search", SearchView.as_view(), name="search"),
    path("error/", ErrorView.as_view(), name="error"),
    path("about-us/", AboutUsView.as_view(), name="about"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("contact-us/", ContactUsView.as_view(), name="contact"),
    path("submit-research/", SubmitResearchView.as_view(), name="submit-research"),
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("refund-policy/", RefundPolicyView.as_view(), name="refund-policy"),
    path("terms-and-conditions/", TermsAndConditionsView.as_view(), name="terms-and-conditions"),
    path("subscribe-newsletter/", SubscribeNewsletterView.as_view(), name="subscribe-newsletter"),
    path("journals", BrowseJournalView.as_view(), name="journals"),
    path("news", NewsListView.as_view(), name="news-list"),
    path("news/<int:pk>/", NewsDetailsView.as_view(), name="news-details"),
    path("announcements", AnnouncementListView.as_view(), name="announcements-list"),
    path("announcements/<int:pk>/", AnnouncementDetailsView.as_view(), name="announcement-details"),
    path("information/<str:url>/", InformationDetailsView.as_view(), name="information-details"),
    path("join/editor/", JoinAsEditorView.as_view(), name="join-as-editor"),
    path("join/reviewer/", JoinAsReviewerView.as_view(), name="join-as-reviewer"),
    path("hard-copy-order/", HardCopyOrderView.as_view(), name="hard-copy-order"),
    
    # Blogs
    path("blogs/", BlogListView.as_view(), name="blog-list"),
    path("blogs/<str:url>/", BlogDetailsView.as_view(), name="blog-details"),

    # Payments
    # path("payments/", PaymentView.as_view(), name="payments"),
    # path("payments/callback/", PaymentCallbackView.as_view(), name="payments-callback"),
    # path("payments/success/", PaymentSuccessView.as_view(), name="payments-success"),
    # path("payments/failed/", PaymentFailedView.as_view(), name="payments-failed"),
    
    # Memberships
    path("membership/apply/", MembershipApplicationView.as_view(), name="membership-apply"),
    path("membership/<str:url>/", MembershipInfoView.as_view(), name="membership-info"),
]

journals/urls.py
from django.urls import path
from journals.views import *

app_name = "journals"

urlpatterns = [
    path("download-article/pdf/", ArticleDownloadView.as_view(), name="article-download"),
    path("download-article/xml/<int:article_id>/", ArticleXMLDownloadView.as_view(), name="article-xml-download"),
    path("<str:url>/search", SearchView.as_view(), name="search"),
    path("<str:url>/about/<str:about_type>/", JournalAboutView.as_view(), name="about"),
    path("<str:url>/archives/", JournalArchiveListView.as_view(), name="archives"),
    path("<str:url>/archives/<str:vol>/<str:issue>/", JournalArchiveDetailsView.as_view(), name="archive-details"),
    path("<str:url>/insights", JournalInsightsView.as_view(), name="insights"),
    path("<str:url>/publications", JournalAuthorPublicationsView.as_view(), name="author-publications"),
    path("<str:url>/policy/<str:policy_url>/", JournalPolicyView.as_view(), name="policy"),

    # Special Issue
    path("<str:url>/special-issue/about/", JournalSpecialIssueAbout.as_view(), name="special-issue-about"),
    path("<str:url>/special-issue/propose/", JournalSpecialIssuePropose.as_view(), name="special-issue-propose"),
    path("<str:url>/special-issue/open/", JournalSpecialIssueOpen.as_view(), name="special-issue-open"),
    path("<str:url>/special-issue/published/", JournalSpecialIssuePublished.as_view(), name="special-issue-published"),
    path("<str:url>/special-issue/<str:vol>/<str:issue>/", JournalSpecialIssueDetails.as_view(), name="special-issue-details"),
    path("<str:url>/<str:vol>/<str:issue>/<str:article_url>/", JournalArticleView.as_view(), name="article"),
    path("<str:url>/", JournalDetailView.as_view(), name="home"),

]

publisher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView


from .sitemap import StaticViewSitemap, ArticleSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "article": ArticleSitemap,
}

urlpatterns = [
    path("sitemap.xml",sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("jet/", include("jet.urls", "jet")),
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("", include("core.urls", namespace="core")),
    path("", include("journals.urls", namespace="journals")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journals/views/archives.py
import os
import re
import requests
import mimetypes
from django.views import View
from django.conf import settings
from django.views.generic import TemplateView
from django.http import (
    FileResponse,
    HttpResponse,
    HttpResponseNotAllowed,
    StreamingHttpResponse,
)
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404

from journals.models import Volume, Issue, Article, ArticleAuthor
from journals.mixins import JournalMixin


class JournalArchiveListView(JournalMixin, TemplateView):
    template_name = "journals/archives/list.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx.update(
            {
                "volumes": Volume.objects.filter(journal=ctx.get("journal")).order_by(
                    "-year"
                )
            }
        )
        return self.render_to_response(ctx)


class JournalArchiveDetailsView(JournalMixin, TemplateView):
    template_name = "journals/archives/details.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        try:
            issue = Issue.objects.get(id=kwargs.get("issue"))
            ctx.update(
                {
                    "articles": Article.objects.filter(issue=issue).order_by(
                        "-published"
                    ),
                    "volume": issue.volume,
                    "issue": issue,
                }
            )
        except:
            return redirect("error")
        return self.render_to_response(ctx)


class JournalArticleView(JournalMixin, TemplateView):
    template_name = "journals/archives/article.html"

    def split_keywords(self, article: Article):
        if article.keywords:
            split_list = re.split(r"(?<!^);|(?!^),", article.keywords)
            return [word.lstrip().rstrip() for word in split_list if word.strip()]
        else:
            return []

    def get(self, request, *args, **kwargs):
        try:
            ctx = self.get_context_data(**kwargs)
            article = Article.objects.get(url=kwargs.get("article_url"))
            article.views += 1
            article.save()
            journal = article.issue.volume.journal
            ctx["recommended"] = Article.objects.filter(
                issue__volume__journal=journal, keywords__icontains=article.keywords
            ).exclude(id=article.id)[:5]

            if not ctx["recommended"]:
                ctx["recommended"] = (
                    Article.objects.filter(issue__volume__journal=journal)
                    .order_by("views")
                    .exclude(id=article.id)[:4]
                )

            affiliations = {}
            aff_counter = 1
            for author in ArticleAuthor.objects.filter(article=article):
                if author.affiliation not in affiliations:
                    affiliations.update({author.affiliation: aff_counter})
                    aff_counter += 1
            authors = []
            for author in ArticleAuthor.objects.filter(article=article):
                temp = author.__dict__
                temp.update(
                    {
                        "full_name": author.full_name,
                        "author_affiliation_id": (
                            affiliations.get(author.affiliation)
                            if author.affiliation
                            else None
                        ),
                    }
                )
                authors.append(temp)
            ctx.update(
                {
                    "authors": authors,
                    "affiliations": affiliations,
                    "article": article,
                    "keywords": self.split_keywords(article),
                }
            )
        except Exception as e:
            print(e)
            return redirect("core:error")
        return self.render_to_response(ctx)


class ArticleXMLDownloadView(View):
    def get(self, request, *args, **kwargs):
        try:
            article = Article.objects.get(id=kwargs.get("article_id"))
            article.downloads += 1
            article.save()

            file_url = article.xml.url

            response = requests.get(file_url, stream=True)
            response.raise_for_status()  # Ensure the request was successful

            filename = os.path.basename(file_url)
            mime_type, _ = mimetypes.guess_type(filename)

            streaming_response = StreamingHttpResponse(
                response.iter_content(chunk_size=8192),
                content_type=mime_type or "application/pdf",
            )
            streaming_response["Content-Disposition"] = (
                f'attachment; filename="{filename}"'
            )
            return streaming_response
        except:
            return redirect("error")


class ArticleDownloadView(View):

    def post(self, request, *args, **kwargs):
        article = Article.objects.get(id=int(request.POST.get("article_id")))
        article.downloads += 1
        article.save()

        self.send_subscriber(request.POST.get("email"))

        try:
            file_url = article.pdf.url

            response = requests.get(file_url, stream=True)
            response.raise_for_status()  # Ensure the request was successful

            filename = os.path.basename(file_url)
            mime_type, _ = mimetypes.guess_type(filename)

            streaming_response = StreamingHttpResponse(
                response.iter_content(chunk_size=8192),
                content_type=mime_type or "application/pdf",
            )
            streaming_response["Content-Disposition"] = (
                f'attachment; filename="{filename}"'
            )
            return streaming_response
        except:
            return redirect(
                reverse(
                    "journals:article",
                    kwargs={
                        "url": article.issue.volume.journal.url,
                        "vol": article.issue.volume.pk,
                        "issue": article.issue.pk,
                        "article_url": article.url,
                    },
                )
            )

    def send_subscriber(self, email):
        IARCON_API_BASE = os.getenv("IARCON_API_BASE")
        url = f"{IARCON_API_BASE}/webapp/subscriber"
        data = {"email": email, "from": "iarconsortium.org"}
        AUTH_TOKEN = os.getenv("IARCON_TOKEN")
        headers = {"Authorization": AUTH_TOKEN, "Content-Type": "application/json"}
        requests.post(url, json=data, headers=headers)
        
    def get(self, request, *args, **kwargs):
        return HttpResponseNotAllowed(["POST"])

journals/views/journal.py
from django.views.generic import TemplateView
from itertools import chain
from django.db.models import Q, Func, Value, CharField, functions
from django.shortcuts import redirect

from core.mixins import PublisherMixin
from journals.models import (
    Indexing,
    EditorialBoard,
    Article,
    JournalNews,
    JournalAnnouncement,
)
from journals.mixins import JournalMixin


class JournalDetailView(JournalMixin, TemplateView):
    template_name = "journals/home.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        articles = Article.objects.filter(issue__volume__journal=ctx.get("journal"))
        ctx.update(
            {
                "editor": EditorialBoard.objects.filter(
                    journal=ctx.get("journal"), editor_type="editor_in_chief"
                ).first(),
                "latest_published": articles.order_by("-published")[:8],
                "most_downloaded": articles.order_by("-downloads")[:8],
                "most_popular": articles.order_by("-views")[:8],
                "news": JournalNews.objects.filter(journal=ctx.get("journal")).order_by(
                    "-created_on"
                )[:2],
                "announcements": JournalAnnouncement.objects.filter(
                    journal=ctx.get("journal")
                ).order_by("-created_on")[:2],
                "indexings": Indexing.objects.filter(
                    journal=ctx.get("journal"), show_in_home=True
                ).order_by("name"),
                "editor_in_chiefs": EditorialBoard.objects.filter(
                    journal=ctx.get("journal"), editor_type="editor_in_chief"
                ),
            }
        )
        return self.render_to_response(ctx)


class JournalInsightsView(JournalMixin, TemplateView):
    template_name = "journals/insights.html"

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        print(ctx)
        indexings = Indexing.objects.filter(journal=ctx.get("journal")).order_by("name")
        ctx.update({"indexings": indexings})
        return self.render_to_response(ctx)


class JournalAboutView(JournalMixin, TemplateView):
    template_name = "journals/about/about.html"
    about_type_map = {
        "aim-and-scope": "Aim & Scope",
        "editorial-board": "Editorial Board",
        "news": "News",
        "announcements": "Announcements",
    }

    def get(self, request, *args, **kwargs):
        about_type = kwargs.get("about_type")
        if about_type not in self.about_type_map.keys():
            return redirect("core:error")
        ctx = self.get_context_data(**kwargs)
        ctx.update(
            {
                "about_type": about_type,
                "about_type_label": self.about_type_map[about_type],
            }
        )

        if about_type == "editorial-board":
            editorial_board = EditorialBoard.objects.filter(journal=ctx.get("journal"))
            ctx.update(
                {
                    "editor_in_chief": editorial_board.filter(
                        editor_type="editor_in_chief"
                    ),
                    "associate_editor": editorial_board.filter(
                        editor_type="associate_editor"
                    ),
                    "editorial_board_member": editorial_board.filter(
                        editor_type="editorial_board_member"
                    ),
                    "advisory_board_member": editorial_board.filter(
                        editor_type="advisory_board_member"
                    ),
                    "managing_editor": editorial_board.filter(
                        editor_type="managing_editor"
                    ),
                    "reviewers": editorial_board.filter(
                        editor_type="reviewer"
                    ),
                }
            )
        elif about_type == "news":
            ctx.update({"news": None})
        elif about_type == "announcements":
            ctx.update({"announcements": None})
        return self.render_to_response(ctx)


class SearchView(JournalMixin, TemplateView):
    template_name = "journals/search/results.html"

    def get(self, request, *args, **kwargs):
        if not request.GET.get("q"):
            return redirect("core:error")
        # try:
        results = None
        ctx = self.get_context_data(**kwargs)
        query = request.GET.get("q")
        all_articles = Article.objects.filter(
            issue__volume__journal=ctx["journal"]
        ).filter(
            Q(title__icontains=query)
            | Q(abstract__icontains=query)
            | Q(keywords__icontains=query)
        )
        author_articles = Article.objects.filter(authors__first_name__icontains=query)
        count = all_articles.count() + author_articles.count()
        articles = list(chain(all_articles, author_articles))
        ctx.update({"query": query, "articles": articles, "count": count})
        return self.render_to_response(ctx)
        # except:
        #     return redirect("core:error")

templates/journals/faq.html
{% extends "_base.html" %}

{% block pagetitle %}FAQs {% endblock %}

{% block content %}
<div class="container min-h-screen py-5 lg:py-10 mb-20">
    <div class="grid grid-cols-1 lg:grid-cols-3">
        <div class="col-span-1">
            <div class="text-2xl lg:text-4xl font-light">Frequently Asked Questions</div>
        </div>
        <div class="col-span-1 lg:col-span-2">
            <div id="accordion-collapse" data-accordion="collapse">
            {% for f in faqs %}
                    <h2 id="accordion-collapse-heading-{{forloop.counter}}">
                        <button type="button" class="flex items-center justify-between w-full p-5 font-medium rtl:text-right text-gray-500 border {% if forloop.last %}border-b{% else %}border-b-0{% endif %} border-gray-200 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 dark:border-gray-700 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 gap-3" data-accordion-target="#accordion-collapse-body-{{ forloop.counter }}" aria-expanded="true" aria-controls="accordion-collapse-body-{{ forloop.counter }}">
                            <span class="text-left">{{ f.question }}</span>
                            <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
                            </svg>
                        </button>
                    </h2>
                    <div id="accordion-collapse-body-{{ forloop.counter }}" class="hidden" aria-labelledby="accordion-collapse-heading-1">
                    <div class="p-5 border {% if forloop.last %}border-b{% else %}border-b-0{% endif %} border-gray-200 dark:border-gray-700 dark:bg-gray-900">
                        <p class="mb-2 text-gray-500 dark:text-gray-400">{{ f.answer|safe }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/journals/home.html
{% extends "journals/base/_base.html" %}

{% block pagetitle %}Home {% endblock %}

{% block extraCSS %}
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
{% endblock %}

{% block content %}
<div class="container mt-5 lg:mt-10">
    <div class="bg-gray-100">
        <div class="container py-10">
            <div class="grid grid-cols-1 lg:grid-cols-4 gap-10">
                <div class="col-span-1 lg:col-span-3">
                    <div class="text-2xl">About the journal</div>
                    <div class="my-3">{{ journal.about|safe }}</div>
                </div>
                <div class="col-span-1">
                    <div class="text-2xl">Indexing Information</div>
                    {% if indexings %}
                    <div class="indexingSlick">
                        {% for index in indexings %}
                        {% if index.image %}
                        <div class="flex justify-center">
                            <img onclick="location.href='{% if index.link %}{{index.link}}{% else %}#{% endif %}'" src="{{ index.image.url }}" class="w-full">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="text-blue-500 cursor-pointer hover:underline underline-offset-4" onclick="location.href='{% url "journals:about" url=journal.url about_type="aim-and-scope" %}'">View full aim &amp; scope</div>
        </div>
    </div>
</div>

<div class="container mt-5 lg:mt-20">
    <div class="grid grid-cols-2 lg:grid-cols-5">
        {% if journal.acceptance_rate %}
        <div class="col-span-1 border-l-2 border-l-primary px-5 py-2">
            <div class="text-3xl">{{ journal.acceptance_rate }}%</div>
            <div class="text-gray-500">Acceptance Rate</div>
        </div>
        {% endif %}
        {% if journal.first_decision %}
        <div class="col-span-1 border-l-2 border-l-primary px-5 py-2">
            <div class="text-3xl">{{ journal.first_decision }} days</div>
            <div class="text-gray-500">Time to first decision</div>
        </div>
        {% endif %}
        {% if journal.review_time %}
        <div class="col-span-1 border-l-2 border-l-primary px-5 py-2">
            <div class="text-3xl">{{ journal.review_time }} days</div>
            <div class="text-gray-500">Review time</div>
        </div>
        {% endif %}
        {% if journal.acceptance_to_publication %}
        <div class="col-span-1 border-l-2 border-l-primary px-5 py-2">
            <div class="text-3xl">{{ journal.acceptance_to_publication }} days</div>
            <div class="text-gray-500">Acceptance to publication</div>
        </div>
        {% endif %}
        <div class="col-span-2 lg:col-span-1 border-l-2 lg:border-l-primary px-5 py-2 hover:text-primary group cursor-pointer"  onclick="location.href='{% url "journals:insights" url=journal.url %}'">
            <div class="flex h-full justify-start items-center text-xl"><i data-feather="arrow-right-circle" class="w-10 h-10 stroke-1 rounded-full bg-primary group-hover:bg-secondary text-white mr-2"></i>View all insights</div>
        </div>
    </div>
</div>


<div class="bg-primary py-5 lg:py-10 mt-5 lg:mt-20 text-light">
    <div class="container">
        <div class="text-2xl">Honorary Editor-in-Chief</div>
        <div class="mt-5 grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-10">
            {% if editor_in_chiefs %}
                {% for editor in editor_in_chiefs %}
                <div class="col-span-1">
                    {% include "journals/blocks/editor.html" %}
                </div>
                {% endfor%}
            {% endif %}
        </div>
        <div class="inline-block mt-5 lg:mt-10 underline-offset-4 hover:underline cursor-pointer" onclick="location.href='{% url "journals:about" url=journal.url about_type="editorial-board"  %}'">View full Editorial Board</div>
    </div>
</div>

<div class="flex justify-center">
    {% include "journals/blocks/ad-space-1.html" %}
</div>

<div class="container mt-5 lg:mt-10">
    <div class="block w-6 h-1 bg-primary"></div>
    <div class="text-2xl mt-2">Articles</div>

    <div class="mt-5 lg:mt-5 mb-4 border-b border-gray-200 dark:border-gray-700">
        <ul class="flex flex-wrap -mb-px font-medium text-center" id="myTab" data-tabs-toggle="#myTabContent" role="tablist">
            <li class="mr-2" role="presentation">
                <button class="inline-block p-4 border-b-2 rounded-t-lg" id="profile-tab" data-tabs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Latest Published</button>
            </li>
            <li class="mr-2" role="presentation">
                <button class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="dashboard-tab" data-tabs-target="#dashboard" type="button" role="tab" aria-controls="dashboard" aria-selected="false">Most Downloaded</button>
            </li>
            <li class="mr-2" role="presentation">
                <button class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="settings-tab" data-tabs-target="#settings" type="button" role="tab" aria-controls="settings" aria-selected="false">Most Popular</button>
            </li>
        </ul>
    </div>
    <div id="myTabContent">
        <div class="hidden p-4 rounded-lg dark:bg-gray-800" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="grid grid-cols-1 lg:grid-cols-4 gap-10">
            {% for article in latest_published %}
                <div class="col-span-1">
                    {% include "journals/blocks/article-box.html" %}
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="hidden p-4 rounded-lg dark:bg-gray-800" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
            <div class="grid grid-cols-1 lg:grid-cols-4 gap-10">
            {% for article in most_downloaded %}
                <div class="col-span-1">
                    {% include "journals/blocks/article-box.html" %}
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="hidden p-4 rounded-lg dark:bg-gray-800" id="settings" role="tabpanel" aria-labelledby="settings-tab">
            <div class="grid grid-cols-1 lg:grid-cols-4 gap-10">
            {% for article in most_popular %}
                <div class="col-span-1">
                    {% include "journals/blocks/article-box.html" %}
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

    <div class="border-t border-t-300 inline-flex justify-start items-center py-5 text-xl group hover:text-primary cursor-pointer">
        <i data-feather="arrow-right-circle" class="h-10 w-10 mr-2 stroke-1 text-white bg-primary rounded-full group-hover:bg-secondary"></i> 
        Read Latest Issue
    </div>
</div>

<div class="container mt-5 lg:mt-10 mb-20">
    <div class="block w-6 h-1 bg-primary"></div>
    <div class="text-2xl mt-2">More from {{ journal.name }}</div>

    <div class="mt-5 lg:mt-5 mb-4 border-b border-gray-200 dark:border-gray-700">
        <ul class="flex flex-wrap -mb-px font-medium text-center" id="myTab" data-tabs-toggle="#myTabContent" role="tablist">
            <li class="mr-2" role="presentation">
                <button class="inline-block p-4 border-b-2 rounded-t-lg" id="news-tab" data-tabs-target="#news" type="button" role="tab" aria-controls="profile" aria-selected="false">News</button>
            </li>
            <li class="mr-2" role="presentation">
                <button class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="announcements-tab" data-tabs-target="#announcements" type="button" role="tab" aria-controls="dashboard" aria-selected="false">Announcements</button>
            </li>
            
        </ul>
    </div>
    <div id="myTabContent">
        <div class="hidden p-4 rounded-lg dark:bg-gray-800" id="news" role="tabpanel" aria-labelledby="news-tab">
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-10">
            {% if news %}
            {% for item in news %}
                <div class="col-span-1 {% if forloop.first %}lg:border-r {% endif %}">
                    <div class="text-gray-500">{{ item.created_on|date:"jS M, Y" }}</div>
                    <div class="mt-3 text-xl cursor-pointer underline-offset-4 hover:underline hover:text-cyan-700" onclick="location.href='{% url "about" about_type="news" %}'">{{ item.heading }}</div>
                </div>
            {% endfor %}
            {% else %}
            <div class="text-gray-500">No News</div>
            {% endif %}
            </div>
        </div>
        <div class="hidden p-4 rounded-lg dark:bg-gray-800" id="announcements" role="tabpanel" aria-labelledby="announcements-tab">
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-10">
                {% if announcements %}
                {% for item in announcements %}
                    <div class="col-span-1 {% if forloop.first %}lg:border-r {% endif %}">
                        <div class="text-gray-500">{{ item.created_on|date:"jS M, Y" }}</div>
                        <div class="mt-3 text-xl cursor-pointer underline-offset-4 hover:underline hover:text-cyan-700" onclick="location.href='{% url "about" about_type="announcements" %}'">{{ item.heading }}</div>
                    </div>
                {% endfor %}
                {% else %}
                <div class="text-gray-500">No Announcements</div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="border-t border-t-300 inline-flex justify-start items-center py-5 text-xl group hover:text-primary cursor-pointer"  onclick="location.href='{% url "journals:about" url=journal.url about_type="news" %}'">
        <i data-feather="arrow-right-circle" class="h-10 w-10 mr-2 stroke-1 text-white bg-primary rounded-full group-hover:bg-secondary"></i> 
        Read all News
    </div>
</div>
{% endblock %}

templates/journals/policy.html
{% extends "journals/base/_base.html" %}

{% block pagetitle %}{{ policy.name }}{% endblock %}

{% block content %}
<div class="container mb-20">
    <div class="py-10 text-xl lg:text-4xl">{{ policy.name }}</div>
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-5">
        <div class="col-span-1 lg:col-span-3">
            <ul class="mt-3">
                {% for p in policies %}
                    <li><a href="{% url 'journals:policy' url=journal.url policy_url=p.url %}" class="block px-3 py-3 underline-offset-4 hover:underline hover:text-cyan-700">{{ p.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-span-1 lg:col-span-6 p-5">
            <div class="text-2xl lg:text-2xl font-light">{{ policy.name }}</div>
            <div class="mt-5">
                {% if policy %}
                    {{ policy.content|safe }}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}